### ISSUE TITLE
ValueError: invalidObjects could not be filled during resurrection process

### ISSUE THREAD

**Issue by davidfarinajr** [ReactionMechanismGenerator/RMG-Py#1367] opened 2018-05-17 16:02 UTC
I've added some chlorine rules etc to my database (as discussed a bit in https://github.com/ReactionMechanismGenerator/RMG-database/pull/257 - will open a PR once we have it closer to working), and I am trying to build a model for chloromethane combustion. After one iteration it fails:

```python
initializing surface ...
surface initialization complete
 DASPK--  AT T (=R1) AND STEPSIZE H (=R2) THE                                    
      In above,  R1 =  0.3886834855475D-38   R2 =  0.6996302739854D-38
 DASPK--  ERROR TEST FAILED REPEATEDLY OR WITH ABS(H)=HMIN                       
Error: Trying to step from time 0.0 to 1e-12 resulted in a solver (DASPK) error
Resurrecting Model...
Error: Model Resurrection has failed
Error: Core species names: ['Ar', 'He', 'Ne', 'N2', 'CH3Cl(1)', 'H2(2)', 'O2(3)', 'HCl(4)', 'Cl(6)', 'CH3(5)']
Error: Core species moles: array([  9.60000000e-01,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   2.00000000e-02,   1.00000000e-02,
         1.00000000e-02,   0.00000000e+00,   1.11803399e-16,
         1.11803399e-16])
Error: Volume: 0.09752875656000003
Error: Core species net rates: array([  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,  -2.94934944e+23,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   2.94934944e+23,
         2.94934944e+23])
Error: Edge species net rates: array([], dtype=float64)
Error: Network leak rates: array([], dtype=float64)
Traceback (most recent call last):
  File "/Users/DavidFarina/Code/RMG-Py//rmg.py", line 173, in <module>
    main()
  File "/Users/DavidFarina/Code/RMG-Py//rmg.py", line 167, in main
    rmg.execute(**kwargs)
  File "/Users/DavidFarina/Code/RMG-Py/rmgpy/rmg/main.py", line 695, in execute
    simulatorSettings = simulatorSettings,
  File "rmgpy/solver/base.pyx", line 520, in rmgpy.solver.base.ReactionSystem.simulate
  File "rmgpy/solver/base.pyx", line 700, in rmgpy.solver.base.ReactionSystem.simulate
ValueError: invalidObjects could not be filled during resurrection process
```

I think the step size of 0.7e-38 seconds and the rate of 2.9e+23 are the cause of the problem, caused by bad kinetics estimates from my database (maybe bad thermo causing a fast reverse reaction), but can anyone help me understand what the `ValueError: invalidObjects could not be filled during resurrection process` means?

**Comment by mjohnson541** [comment] 2018-06-01 14:27
Closing with merge of #1371

**Closed** 2018-06-01 14:27 UTC
Labels: Type: Error

**Comment by sthakris** [comment] 2023-02-08 02:34
Is this has been solved. I have got exact same error for nitogen containing species.

**Comment by mjohnson541** [comment] 2023-02-08 07:05
The issue is solved in the sense that the error occurs when expected. We expect this error to occur if RMG repeatedly fails to solve a reactor. This error almost always indicates a problem with the thermochemistry estimates, although it can also be an issue with the kinetic estimates.
