### ISSUE TITLE
AttributeError: 'list' object has no attribute 'label'

### ISSUE THREAD

**Issue by Prosbin** [ReactionMechanismGenerator/RMG-Py#821] opened 2016-11-16 06:40 UTC
Hi,
My simulation showed the error above whilst running pyrolysis of PET (input file is attached: pet.py). Please help me get past the error. The screen shot is also attached. Thanks!

[pet.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/593892/pet.txt)

![codes](https://cloud.githubusercontent.com/assets/23437345/20337135/60689d72-abcf-11e6-84fd-dcf283cb979c.jpg)

**Comment by rwest** [comment] 2016-11-16 07:03
Using http://rmg.mit.edu/molecule_search to draw a picture of the adjacency list you have for your "PET" species gives this:
![pet](https://cloud.githubusercontent.com/assets/93807/20337400/c5dae10a-ab85-11e6-93ac-b4ac89b71446.png)

I expect the problem is that there are two separate molecules not joined by any bonds, as part of the same species.
I presume you're trying to model poly(ethylene terephthalate). Probably the name to structure translator grabbed the monomer units, eg as listed here 
http://polymerdatabase.com/polymers/polyethyleneterephthalate.html
Putting in a whole polymer that is several monomer units long is most likely to overwhelm RMG because the molecule is too large and there are too many things it can do. We could instead try something like
![en](https://cloud.githubusercontent.com/assets/93807/20337637/16ed5888-ab87-11e6-882d-67b8804695aa.png)
which has the SMILES string `C(=O)c1ccc(cc1)C(=O)OCC` though I have not checked carefully that this is the most appropriate structure.

When I put that in your input file, it runs without error, at least for a little while.  I'll let someone else tackle the next problem that I fear is waiting around the corner...

**Comment by Prosbin** [comment] 2016-11-16 09:48
Thanks @rwest , you are right about the dual nature of the structure. I will try this new structure and compare the results obtained with experimental findings. I hope there is a close match; I also hope no more errors are encountered with this new structure. Thank you again; I will give you feedback on this new structure.

**Comment by rwest** [comment] 2016-11-16 23:34
Depending what you are trying to achieve, you could also put the two monomer units in as separate species. I'll close this issue now, as we've identified the problem.

**Closed by rwest** 2016-11-16 23:34 UTC

**Comment by Prosbin** [comment] 2016-11-17 05:45
Hi @rwest ,
Please let me know if you were able to generate any results with the new structure you tried; mine stopped making visible progress about 3.5 hours ago. No error message came up; it was just there, so I decided to start afresh. But, if yours worked, please send me the result. You may send it to: prosbin@gmail.com. Thanks.
