### ISSUE TITLE
rmgpy.data.kinetics.common.UndeterminableKineticsError:

### ISSUE THREAD

**Issue by KEHANG** [ReactionMechanismGenerator/RMG-Py#253] opened 2014-07-14 19:52 UTC
anyone familiar with this kind of error? I'm running model for combustion of (CH4, C2H6, C3H8) in oxygen-rich air (O2:N2=3:1). Almost all the settings in input file are default. It turns out:
Adding species `[CH]=C[O](307)` to model core
Traceback (most recent call last):
........

``` python
  File "/home/hkh12/code/RMG-Py/rmgpy/data/kinetics/groups.py", line 168, in getReactionTemplate
    raise UndeterminableKineticsError(reaction, message=msg)
rmgpy.data.kinetics.common.UndeterminableKineticsError: (Reaction(reactants=[Molecule(SMILES="C#C"), Molecule(SMILES="[O]")], products=[Molecule(SMILES="[CH]=C[O]")], pairs=[[Molecule(SMILES="C#C"), Molecule(SMILES="[CH]=C[O]")], [Molecule(SMILES="[O]"), Molecule(SMILES="[CH]=C[O]")]]), 'Kinetics could not be determined. Unable to find matching template for reaction <Molecule "C#C"> + <Molecule "[O]"> <=> <Molecule "[CH]=C[O]"> in reaction family <KineticsGroups "R_Addition_MultipleBond/groups">.Trying to match [<Entry index=1 label="R_R">, <Entry index=2 label="YJ">] but matched [<Entry index=840 label="Ct-H_Ct-H">]')
```

**Comment by alongd** [comment] 2016-10-30 18:17
I got a similar error (for a different reaction family, 1+2_Cycloaddition):
```
Traceback (most recent call last):
  File "D:\Code\RMG-Py\/rmg.py", line 152, in <module>
    rmg.execute(**kwargs)
  File "D:\Code\RMG-Py\rmgpy\rmg\main.py", line 602, in execute
    self.reactionModel.enlarge(objectToEnlarge)
  File "D:\Code\RMG-Py\rmgpy\rmg\model.py", line 597, in enlarge
    newReactions = network.exploreIsomer(species)
  File "D:\Code\RMG-Py\rmgpy\rmg\pdep.py", line 297, in exploreIsomer
    newReactions = react((isomer,))
  File "D:\Code\RMG-Py\rmgpy\rmg\react.py", line 75, in react
    combos
  File "D:\Code\RMG-Py\rmgpy\scoop_framework\util.py", line 154, in map_
    return map(WorkerWrapper(args[0]), *args[1:], **kwargs)
  File "D:\Anaconda\envs\rmg_env\lib\site-packages\scoop-0.7.2.0-py2.7.egg\scoop\fallbacks.py", line 49, in wrapper
  File "D:\Code\RMG-Py\rmgpy\scoop_framework\util.py", line 112, in __call__
    return self.myfn(*args, **kwargs)
  File "D:\Code\RMG-Py\rmgpy\rmg\react.py", line 96, in reactMolecules
    rxns = family.generateReactions(molecules)
  File "D:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1349, in generateReactions
    reactionList.extend(self.__generateReactions(reactants, forward=False))
  File "D:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1567, in __generateReactions
    reaction.template = self.getReactionTemplateLabels(reaction)
  File "D:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1817, in getReactionTemplateLabels
    template = self.getReactionTemplate(reaction)
  File "D:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1675, in getReactionTemplate
    return self.groups.getReactionTemplate(reaction)
  File "D:\Code\RMG-Py\rmgpy\data\kinetics\groups.py", line 163, in getReactionTemplate
    raise UndeterminableKineticsError(reaction, message=msg)
rmgpy.data.kinetics.common.UndeterminableKineticsError: (Reaction(reactants=[Molecule(SMILES="C#C"), Molecule(SMILES="[NH]")], products=[Molecule(SMILES="C1=CN1")], degeneracy=2, pairs=[[Molecule(SMILES="C#C"), Molecule(SMILES="C1=CN1")], [Molecule(SMILES="[NH]"), Molecule(SMILES="C1=CN1")]]), 'Kinetics could not be determined. Unable to find matching template for reaction <Molecule "C#C"> + <Molecule "[NH]"> <=> <Molecule "C1=CN1"> in reaction family <KineticsGroups "1+2_Cycloaddition/groups">.Trying to match [<Entry index=1 label="elec_def">, <Entry index=2 label="multiplebond">] but matched [<Entry index=44 label="mb_tb_unsub">]')
```

**Comment by nyee** [comment] 2016-10-30 18:22
The error says you are only matching mb_tb_unsub, which is on the multiple bond tree, so it must be corresponding to C#C. It looks like [NH] is not matching the even the top node of the elec_def tree. Can't look now, but my guess would be either that the root either lacks some nitrogen atom types or the multiplicity is not included.

**Comment by alongd** [comment] 2016-10-30 18:28
I'll look at the nitrogen representation in the tree.
But looking first at the recipe of the 1+2_Cycloaddition family, I see that the attacking species loses its lone pair (`['LOSE_PAIR', '*3', '1']`). Shouldn't it be loosing two radicals, since in this case [NH] is reacting? The product RMG predicts is `C1=CN1`, which is not a radical.

**Comment by alongd** [comment] 2016-10-30 18:38
I guess we're seeing here the singlet form NH(S), I can't tell for sure from the SMILES only. But following the recipe, probably it is the recently added N1s (I'm working on the nitrogen branches in Py and database)

**Comment by nyee** [comment] 2016-10-30 18:43
It looks like the problem is imidogen_singlet is defined with N3s, which would be the correct atomtype under the old system before we added N1s. I think if you just change that N3s is to N1s it'll work.

**Comment by alongd** [comment] 2016-10-31 00:00
I changed to N1s, as you recommended, and this is now solved.
Should we still keep this issue open, since it's a more general problem (see #225, #386), or close it noting that if this issue rises again, the groups (& atom types) should be checked in the related reaction family?

**Comment by mliu49** [comment] 2018-05-17 18:18
Closing since this is a family specific issue. New instances should be documented in separate issues.

**Closed by mliu49** 2018-05-17 18:18 UTC
