### ISSUE TITLE
What elements are supported in CanTherm (Arkane)?

### ISSUE THREAD

**Issue by cjmcgill** [ReactionMechanismGenerator/RMG-Py#1494] opened 2018-10-18 00:42 UTC
### Topic
General area which your question is related to.
 - [ ] CanTherm

### Context
I would like to use CanTherm to calculate thermo for some organometallics.

### Question
What elements are currently supported in CanTherm? Is it limited to the elements in RMG? Could the load geometry from QC files implementation be more limited than CanTherm generally?

**Comment by alongd** [comment] 2018-10-18 14:34
The elements supported by CanTherm depend on the model chemistry (see the documentation: http://reactionmechanismgenerator.github.io/RMG-Py/users/cantherm/input.html#model-chemistry).
However, one can specify a dictionary of Atomic Energy Corrections, see an example on the same page I referred above.
I hope that helps, let us know if you have other questions or encounter any issues.

(I did not understand the final question "Could the load geometry from QC files implementation be more limited than CanTherm generally?")

**Comment by cjmcgill** [comment] 2018-10-18 15:14
In my attempt, I specified the dictionary of Atomic Energy Corrections for the atoms in my molecule (C,H,O,Sn). I got back this error.

`File "C:\Anaconda\envs\rmg_env\lib\site-packages\rmgpy\cantherm\gaussian.py", line 160, in loadGeometry
    raise NotImplementedError('Atomic number {0:d} not yet supported in loadGeometry().'.format(number[i]))
NotImplementedError: Atomic number 50 not yet supported in loadGeometry().`

**Comment by alongd** [comment] 2018-11-02 20:57
@cjmcgill, this should be addressed via #1473.

**Comment by alongd** [comment] 2018-11-14 13:39
@cjmcgill, you're right, the fix we added allows Cantherm to read all elements (and ascribe correct masses) from the electronic structure software. To calculate thermo, we would also need the atom's heat of formation (in addition to atomic energy corrections that you already have). We recently added Iodine, perhaps you could come up with values for Tin, we'll happily review them and add them to Cantherm.

Here's some additional information from the code's comments:

```python
# Step 2: Atom energy corrections to reach gas-phase reference state
        # Experimental enthalpy of formation at 0 K
        # See Gaussian thermo whitepaper at http://www.gaussian.com/g_whitepap/thermo.htm)
        # Note: these values are relatively old and some improvement may be possible by using newer values, particularly for carbon
        # However, care should be taken to ensure that they are compatible with the BAC values (if BACs are used)
        # The enthalpies listed here should correspond to the allowed elements in atom_num_dict
        # Iodine value is from Cox, J. D., Wagman, D. D., and Medvedev, V. A., CODATA Key Values for Thermodynamics, Hemisphere Publishing Corp., New York, 1989.
        atomHf = {'H': 51.63,
                  'Li': 37.69, 'Be': 76.48, 'B': 136.2, 'C': 169.98, 'N': 112.53, 'O': 58.99, 'F': 18.47,
                  'Na': 25.69, 'Mg': 34.87, 'Al': 78.23, 'Si': 106.6, 'P': 75.42, 'S': 65.66, 'Cl': 28.59, 'I':24.04}
        # Thermal contribution to enthalpy Hss(298 K) - Hss(0 K) reported by Gaussian thermo whitepaper
        # This will be subtracted from the corresponding value in atomHf to produce an enthalpy used in calculating the enthalpy of formation at 298 K
        atomThermal = {'H': 1.01,
                       'Li': 1.1, 'Be': 0.46, 'B': 0.29, 'C': 0.25, 'N': 1.04, 'O': 1.04, 'F': 1.05,
                       'Na': 1.54, 'Mg': 1.19, 'Al': 1.08, 'Si': 0.76, 'P': 1.28, 'S': 1.05, 'Cl': 1.1, 'I':1.48}
        # Total energy correction used to reach gas-phase reference state
        # Note: Spin orbit coupling no longer included in these energies, since some model chemistries include it automatically
```

**Comment by alongd** [comment] 2018-11-18 19:17
Thanks for referencing the codata source. The data in the code could principally also be changed by users ([it's right here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/arkane/statmech.py#L758)) if RMG was installed by source. I'd also happily add relevant entries from the codata table for everyone's' benefit (and will update here once done)
(If you upgrade our code or wait for the next release, please note that Cantherm was recently renamed as Arkane).

**Comment by alongd** [comment] 2018-11-19 20:02
@cjmcgill, let us know whether this issue is now fixed on the current master branch

**Comment by cjmcgill** [comment] 2018-11-20 00:34
`File "/home/cjmcgill/RMG/RMG-Py/arkane/main.py", line 267, in execute
    job.execute(outputFile=outputFile, plot=self.plot)
  File "/home/cjmcgill/RMG/RMG-Py/arkane/statmech.py", line 192, in execute
    self.load()
  File "/home/cjmcgill/RMG/RMG-Py/arkane/statmech.py", line 379, in load
    'Element {} is not yet supported.'.format(_rdkit_periodic_table.GetElementSymbol(atom_num))
Exception: Element Sn is not yet supported.`

I seem to be getting the same message still

RMG-Py 2.1.0-1517-gd2c282a

**Comment by alongd** [comment] 2018-11-20 01:19
OK. Pleade upload an input file(s) to reproduce this error

**Comment by cjmcgill** [comment] 2018-11-20 01:34
Yes of course. I'm attaching the relevant input files, including the Gaussian log file.

[Inputs.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2597689/Inputs.zip)

**Comment by mliu49** [comment] 2018-11-20 01:57
There is a hard-coded dictionary of supported elements [here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/arkane/statmech.py#L62) which might need to be updated. I haven't confirmed that this is the cause though.

**Comment by alongd** [comment] 2018-11-20 02:17
Thanks @mliu49, I believe you're right

**Comment by alongd** [comment] 2018-11-20 19:10
@cjmcgill, let us know if now Arkane works for Sn as expected

**Comment by cjmcgill** [comment] 2018-11-20 23:30
Updated and it worked. I got reasonable looking results and no errors, so things are looking good. Thanks!

This was just an input for thermo. I will try it again a little later on with a canonical transition state using tin and verify if it works there too.

**Comment by alongd** [comment] 2018-11-21 01:15
Glad to hear! Please do let us know :)

**Closed by alongd** 2018-11-21 01:15 UTC
Labels: Arkane

**Comment by cjmcgill** [comment] 2018-11-30 04:36
The thermo calculations and transition state theory calculations seem to work for tin atoms, but there are some errors that I think might be unrelated to the tin atom. I will start a new report for those.

**Comment by cjmcgill** [comment] 2019-06-23 23:38
It appears that the site I referenced earlier for the thermo data is no longer available. Here is a new website reference that has the same information. There's a formal book reference for the data at that site as well.

http://www.codata.info/resources/databases/key1.html
