### ISSUE TITLE
Unable to calculate degeneracy for Intra_Diels_alder

### ISSUE THREAD

**Issue by cfgoldsmith** [ReactionMechanismGenerator/RMG-Py#617] opened 2016-03-17 18:48 UTC
In trying to build a mechanism for 2-nitrodiphenylamine, RMG-Py proposes an Intra Diels Alder reaction, but it crashes when it cannot calculate the degeneracy:

``` python
Error: Molecule "C123C4(N2)C(=CC(C1C=CC=C3)C=C4)ON=O"
Error: Molecule "c1(c(cccc1)ON=O)Nc1ccccc1"
Traceback (most recent call last):
  File "../../../rmg.py", line 165, in <module>
    rmg.execute(inputFile, output_dir, **kwargs)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/rmg/main.py", line 636, in execute
    bimolecularReact=self.bimolecularReact)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/rmg/model.py", line 748, in enlarge
    self.processNewReactions(self.react(database, self.core.species[i]), self.core.species[i], None)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/rmg/model.py", line 649, in react
    reactionList.extend(database.kinetics.generateReactionsFromFamilies([moleculeA], products=None, only_families=only_families))
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/kinetics/database.py", line 419, in generateReactionsFromFamilies
    reactionList.extend(family.generateReactions(reactants))
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/kinetics/family.py", line 1341, in generateReactions
    reactionList.extend(self.__generateReactions(reactants, forward=False))
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/kinetics/family.py", line 1571, in __generateReactions
    reaction.degeneracy = self.calculateDegeneracy(reaction)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/kinetics/family.py", line 1369, in calculateDegeneracy
    'but generated {2}').format(reaction, self.label, len(reactions)))
rmgpy.data.kinetics.common.KineticsError: Unable to calculate degeneracy for reaction <Molecule "C123C4(N2)C(=CC(C1C=CC=C3)C=C4)ON=O"> <=> <Molecule "c1(c(cccc1)ON=O)Nc1ccccc1"> in reaction family Intra_Diels_alder. Expected 1 reaction but generated 2
```

NOTE: this mechanism was generated using Richard's "resonance" branch (see issue #590 and Richard's patch #609)

**Comment by alongd** [comment] 2016-03-17 18:59
Hi, see similar issue we had: #545.
As a temporary solution, I commented-down this error (ccfdc7e8f54ff548bffaa3ccaa4bf6f9dac9a501), since I experienced it only for insignificant edge species. Of course, this is still unresolved, and #545 is still open.

**Comment by cfgoldsmith** [comment] 2016-03-17 21:16
Thanks, Alon. I'll give that a shot.

**Comment by alongd** [comment] 2017-04-28 20:50
duplicate of #545

**Closed by alongd** 2017-04-28 20:50 UTC
Labels: Resonance
