### ISSUE TITLE
Numpy raises a FutureWarning in Arkane

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#1697] opened 2019-08-19 17:20 UTC
# Bug Description
[self.thermo = species.thermo.as_dict()](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/arkane/common.py#L181) in Arkane common.py raises the following warning:
```
RMG-Py/arkane/common.py:181: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  self.thermo = species.thermo.as_dict()
```

# Additional Info
According to [StackOverflow](https://stackoverflow.com/questions/40659212/futurewarning-elementwise-comparison-failed-returning-scalar-but-in-the-futur), it is caused by comparisons between Python variables and numpy variables. A source for this warning could be from ['polynomials' in output_dict:](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/thermo/nasa.pyx#L257).

**Comment by amarkpayne** [comment] 2019-08-19 18:47
This started popping up after #1643, I'll take a look

**Comment by amarkpayne** [comment] 2019-08-20 12:05
The issue has to do with [this line here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/3846fcce701f2a5fd12dbfa429687e9fcd647298/rmgpy/rmgobject.pyx#L57), where we check that the attribute is not an empty string (in which case we don't want to output this attribute to the YAML file). This throws a warning because numpy first tries to check every element of the array to see if it is `''`.

I have made a fix for this and confirmed that the warning statements go away. The commit is currently located in #1694.

**Closed** 2019-09-26 14:19 UTC
Labels: Status: Fixed in PR, Type: Risk of Error
