### ISSUE TITLE
Error Creating Environment in Windows Anaconda Source Install

### ISSUE THREAD

**Issue by cjmcgill** [ReactionMechanismGenerator/RMG-Py#1507] opened 2018-11-13 02:46 UTC
### Bug Description
Message is occurring as I go through the instructions for installing from source using Anaconda with Windows.

Installed anaconda (for python 2.7) and git, then cloned the files from github, then added the anaconda scripts to my path so the conda command could run. These steps seemed outwardly successful. Then ran the step `conda env create -f environment_windows.yml`. Output was the following

```
Solving environment: failed

ResolvePackageNotFound:
  - dde
  - keras=1.2.2
```

So this would seem like I'm missing some rmg pieces needed to build the environment?

### Installation Information

 - OS: Windows 10
 - Installation method: installation from source with anaconda
 - RMG version information: 2.1.0-1503-gb17e3d5a2

**Comment by mliu49** [comment] 2018-11-13 16:44
The problem is that there's no Windows binary for keras 1.2.2.

We officially decided to stop actively supporting Windows a while ago, but there hadn't been any changes which broke RMG on Windows, until this.

I think there are a couple of different options in terms of development:
- Create Windows package for keras 1.2.2
- Modify dde to use a newer version of keras, with existing Windows binaries
- Modify RMG such that it works without the presence of dde
- Do nothing, with RMG no longer working on Windows at all from this point on

You are welcome to contribute changes if you would like. Otherwise, it will depend on how much time other developers can devote to this. Perhaps @cgrambow can comment as well. My suggestion to you right now is to revert to an older version of RMG, before the machine learning changes were implemented (6ac044e35a49b060db0a418995bd3f7c33ee1512).

**Comment by cjmcgill** [comment] 2018-11-13 16:58
I would revert to an older version of RMG or go with a binaries install, except that I'm seeking a version of Cantherm that can support more atom types, per Issue #1494 . I think I will try for a linux install on a different machine. Now that there's a known issue with the windows source install, I recommend changing the installation documentation to reflect that.

**Comment by mliu49** [comment] 2018-11-13 17:09
Ah, I see. The Cantherm updates that you're looking for were merged before the machine learning changes, so the commit I referenced should have what you need. You can either checkout or reset to 6ac044e35a49b060db0a418995bd3f7c33ee1512 on RMG-Py. The RMG-database version isn't as crucial, so current master should work without any problems.

We will work on updating the documentation.

**Comment by JacksonBurns** [comment] 2023-05-12 00:22
The installation methods discussed in this issue are no longer supported. Closing as stale.

**Closed by JacksonBurns** 2023-05-12 00:22 UTC
Labels: Platform: Windows, Type: Environment
