### ISSUE TITLE
accurate degeneracy w/ resonance structures

### ISSUE THREAD

**Issue by goldmanm** [ReactionMechanismGenerator/RMG-Py#1293] opened 2018-02-16 21:08 UTC
@alongd mentioned a case where degeneracy is not accurate in ReactionMechanismGenerator/RMG-database#248.

Currently, in the degeneracy algorithm, if all the molecules in a reaction are isomorphic but not identical, the reactions are considered degenerate. However, if a molecule has resonance structures which don't interact with the reacting site, this algorithm may still treat them as isomorphic but not identical and increase the degeneracy. 

To correct for this issue, we should only check that the atom ids of reacting sites are identical in the calculate degeneracy method instead of checking the entire molecule. 

to describe the weird comparison terms:

isomorphic = checks that the graph is the same, looking at bond order, isotope, atom type, etc.
identical = almost the same as isomorphic but also checks the atomID.

**Comment by mliu49** [comment] 2018-02-16 22:02
I hope you don't mind me fixing your link.

This is an interesting observation, but I don't fully understand your explanation. I would definitely like to look into this more.

**Comment by alongd** [comment] 2018-02-19 04:37
I'd like to add my understanding of the situation as well, as recently discussed with @goldmanm 

Our discussion primarily concerned the `[NH] + [O-][N+]=O <=> [NH][N+](=O)[O-]` birad-R recombination reaction as an example:
![image](https://user-images.githubusercontent.com/16158262/36362081-6248962a-14ff-11e8-8360-0c79436791c4.png) + ![image](https://user-images.githubusercontent.com/16158262/36362073-58a54258-14ff-11e8-9d57-9431ee4fb9b2.png) <=> ![image](https://user-images.githubusercontent.com/16158262/36362062-468a89c0-14ff-11e8-915f-74a0eaeb7008.png)

NO2 is described by two distinctive contributing Lewis structures, but if we account for isomorphic structures as well, we get four:

![image](https://user-images.githubusercontent.com/16158262/36325750-d74bed6c-1326-11e8-85ff-5e5c21613235.png)
![image](https://user-images.githubusercontent.com/16158262/36325755-db703f06-1326-11e8-845b-623bf6836ba4.png)
![image](https://user-images.githubusercontent.com/16158262/36325758-de863aa6-1326-11e8-8826-b5e3219998b0.png)
![image](https://user-images.githubusercontent.com/16158262/36325762-e07458ac-1326-11e8-89d1-479f6fac1ec2.png)

For the above reaction, only the first two are relevant.
There is only one way in which the N atom can react in this template, regardless of our single/double bond representation for the bonding with the other two O atoms. In other words, we count two structures with a radical N atom since we assign different atom IDs to the oxygens, while in fact these structures should be though of as identical in this context (and not only isomorphic).

The above becomes clearer when we look at the reactivity at the radical O site: There's a x2 higher probability that this site will react in any relevant template than having just one O atom in the species (given that all other considerations are artificially kept the constant).

Therefore, keeping the physical reality in mind, the degeneracy of the original reaction in the example is 1, not 2.

@goldmanm also explained this from the perspective of the definition of reaction symmetry:
The reaction symmetry is defined as the symmetry of the reactants over the symmetry of the TS.
For reaction (a) below, this equals 2 / 2 = 1
For reaction (b) below, this equals 2 / 1 = 2

(a) ![image](https://user-images.githubusercontent.com/16158262/36362081-6248962a-14ff-11e8-8360-0c79436791c4.png) + ![image](https://user-images.githubusercontent.com/16158262/36362073-58a54258-14ff-11e8-9d57-9431ee4fb9b2.png) <=> ![image](https://user-images.githubusercontent.com/16158262/36362062-468a89c0-14ff-11e8-915f-74a0eaeb7008.png)

(b) ![image](https://user-images.githubusercontent.com/16158262/36362081-6248962a-14ff-11e8-8360-0c79436791c4.png) + ![image](https://user-images.githubusercontent.com/16158262/36362392-5170ab5a-1502-11e8-9071-957de4a771fd.png) <=> ![image](https://user-images.githubusercontent.com/16158262/36362398-671a9862-1502-11e8-85c6-58da97883df3.png)

Since reaction degeneracy is a convenient computational way to approximate and represent the reaction symmetry, we get that the degeneracy for (a) is indeed 1, while the degeneracy for (b) is 2, both in accordance with the above claims.

In this context, I'll echo what @goldmanm wrote above: "if a molecule has resonance structures which don't interact with the reacting site, this algorithm may still treat them as isomorphic but not identical and increase the degeneracy."
This is exactly the case here. The following resonance transformation does not modify the reactive site:
![image](https://user-images.githubusercontent.com/16158262/36325750-d74bed6c-1326-11e8-85ff-5e5c21613235.png) <=> ![image](https://user-images.githubusercontent.com/16158262/36325755-db703f06-1326-11e8-845b-623bf6836ba4.png)
unlike the second pair in this transformation which does (if atom IDs are ascribed, and the Os are differentiable):

![image](https://user-images.githubusercontent.com/16158262/36325758-de863aa6-1326-11e8-8826-b5e3219998b0.png) <=> ![image](https://user-images.githubusercontent.com/16158262/36325762-e07458ac-1326-11e8-89d1-479f6fac1ec2.png)

We could further complicate things and think of cases where one of the O atoms is substituted by a different group (or a different isotope) -- in which case the single/double bonding notation does matter since the reaction "looks" these bonds in place. However, since the products would be different, the degeneracy should be 1 and @goldmanm's rule still applies.

**Comment by mliu49** [comment] 2018-02-20 17:17
I looked into this more, and I'm pretty sure the degeneracy algorithm is working as intended. The entire point of atom IDs and the isIdentical check was to address cases like this.

The degeneracy for this reaction should be 1, but the reason that it's 2 is due to resonance structure generation, not degeneracy.

Like you've shown, NO2 has two relevant resonance structures for this reaction, where either O can have the double bond. After the recombination, you would expect those to resonance structures to still exist (after all, they don't participate in the reaction).

However, RMG only generates two resonance structures for the product, and only one O ever has a double bond (the one that had it to start with):

![image](https://user-images.githubusercontent.com/10817103/36437955-76517d16-1636-11e8-9329-9e6b9d826526.png)

![image](https://user-images.githubusercontent.com/10817103/36437968-7a8181c4-1636-11e8-964c-2ee75ce59b57.png)

This means that RMG will not recognize the reactions from the two reactant structures as being identical. It's important to realize that the isIdentical check operates across all resonance structures. If you have resonance structure A reacting to form B and resonance structure C reacting to from D, B and D will never be identical to each other directly. However, if B has a resonance structure that is identical to D, then the two reactions will be identical and not contribute to degeneracy. The issue here is that RMG does not properly enumerate all the resonance structures for B, so it doesn't find the one that's identical to D.

**Comment by alongd** [comment] 2018-02-26 21:30
I see. Thanks for the insight!
So this should be a transformation like the `N5ddc <=> N5tc` one where the intermediate structure is forbidden by atomType (+2 formal charge), so we directly allow it.
I see why the two O atoms behave differently in RMG, while physically they should have identical characteristics.

**Comment by alongd** [comment] 2018-06-27 02:01
resolved by #1348

**Closed by alongd** 2018-06-27 02:01 UTC
Labels: Module: Resonance, Topic: Kinetics
